name: SOArmazem
version: ${project.version}
main: me.soekd.soarmazem.Main
depend: [PlotSquared,Vault]
author: SOekd
website: https://github.com/SOekd
commands:
  storage:
    aliases: [armazem]
    description: Abra o armazem do seu terreno
  storageadmin:
    aliases: [armazemadmin]
    description: Altere as configuracoes do terreno
